import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service | Repurposer AI",
    description: "Terms and conditions for using Repurposer AI.",
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background gradient-mesh">
            <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
                <h1 className="text-4xl font-bold tracking-tight mb-8 bg-gradient-to-r from-violet-400 to-indigo-400 bg-clip-text text-transparent">
                    Terms of Service
                </h1>

                <div className="prose prose-invert max-w-none text-muted-foreground">
                    <p className="text-lg text-foreground mb-6">
                        Last updated: {new Date().toLocaleDateString()}
                    </p>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold text-foreground mb-4">1. Acceptance of Terms</h2>
                        <p className="mb-4">
                            By accessing or using Repurposer AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold text-foreground mb-4">2. Use of Service</h2>
                        <p className="mb-4">
                            You agree to use Repurposer AI only for lawful purposes. You represent that you own the rights to the content you submit or have the necessary permissions to repurpose it.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold text-foreground mb-4">3. AI-Generated Content</h2>
                        <p className="mb-4">
                            Content generated by our AI is provided "as is." While we strive for high quality, we make no guarantees about the accuracy, uniqueness, or suitability of the generated content for your specific needs. You are responsible for reviewing and editing all content before publishing.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold text-foreground mb-4">4. Intellectual Property</h2>
                        <p className="mb-4">
                            You retain all rights to your original content. You are granted a non-exclusive right to use the generated output for your personal or commercial purposes.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold text-foreground mb-4">5. Disclaimer of Warranties</h2>
                        <p className="mb-4">
                            The service is provided on an "as available" basis without warranties of any kind, whether express or implied.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-foreground mb-4">6. Limitation of Liability</h2>
                        <p>
                            In no event shall Repurposer AI be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the service.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
